<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>com.caios.soundpad.native</AssemblyName>
    <RootNamespace>UlanziSoundpadNative</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SoundpadConnector">
      <HintPath>libs\SoundpadConnector.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>libs\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
